// ============================================================
// LANGUAGES.JS - Complete Language Data for All Sections
// ============================================================

const translations = {
  en: {
    // ===== NAVIGATION =====
    navHome: 'Home',
    navProducts: 'Products',
    navIngredients: 'Ingredients',
    navBusiness: 'Business',
    navPackages: 'Packages',
    navResources: 'Resources',
    navJoin: 'Join Now',
    
    // ===== HERO =====
    heroEyebrow: 'Life Nutrics South Sudan International Hub',
    heroTitle: 'Elevating',
    heroTitleAccent: 'Lives',
    heroSub: 'Health · Wealth · Lifestyle',
    heroDesc: 'A premier wellness enterprise rooted in natural functional foods, dedicated to transforming communities across South Sudan and beyond.',
    heroBtnProducts: 'Explore Products',
    heroBtnBusiness: 'Business Opportunity',
    heroStat1Num: '18',
    heroStat1: 'Active Ingredients',
    heroStat2Num: '200+',
    heroStat2: 'Ailments Addressed',
    heroStat3Num: '2025',
    heroStat3: 'Established in Juba',
    
    // ===== NUTRIKA DETAILS =====
    nutrikaLabel: 'About Nutrika',
    nutrikaTitle: 'What is Nutrika?',
    nutrikaIntro: 'Nutrika is a premium functional food therapy product formulated with 18 powerful natural ingredients and enhanced with three advanced food technologies from France, Japan, and China.',
    nutrikaDesc: 'It is designed to support the body at a cellular level, helping restore normal body function through nutrition-based science.',
    nutrikaNot: 'Nutrika is not:',
    nutrikaNot1: 'A herbal mixture',
    nutrikaNot2: 'A synthetic supplement',
    nutrikaNot3: 'A pharmaceutical drug that only suppresses symptoms like painkillers',
    nutrikaInstead: 'Instead, Nutrika falls under the category of:',
    nutrikaInstead1: 'Functional Food Therapy',
    nutrikaInstead2: 'Cellular Nutrition Science',
    nutrikaFocus: 'It focuses on nourishing, protecting, and supporting the body\'s natural repair systems — rather than masking symptoms.',
    nutrikaHow: 'How Nutrika Works in the Body',
    nutrikaHowDesc: 'Nutrika works at the cellular level, where all chronic conditions begin.',
    nutrikaHowDesc2: 'Many chronic challenges — such as inflammation, joint pain, nerve damage, high blood sugar, fatigue, weak immunity, and organ dysfunction — start when cells become:',
    nutrikaCell1: 'Damaged',
    nutrikaCell2: 'Inflamed',
    nutrikaCell3: 'Oxidized',
    nutrikaCell4: 'Aged',
    nutrikaCell5: 'Nutrient deficient',
    nutrikaSupport: 'Nutrika supports the body by:',
    nutrikaSupport1: 'Supporting repair of damaged cells',
    nutrikaSupport2: 'Promoting healthy cell regeneration',
    nutrikaSupport3: 'Encouraging rejuvenation of aging cells',
    nutrikaSupport4: 'Supporting detoxification pathways',
    nutrikaSupport5: 'Helping restore normal metabolic balance',
    nutrikaSupport6: 'Supporting blood purification and circulation',
    nutrikaSupport7: 'Enhancing the body\'s natural healing response',
    nutrikaSupportDesc: 'Instead of just covering symptoms, Nutrika focuses on addressing underlying cellular dysfunction through advanced nutritional science.',
    nutrikaTech: 'The 3 Powerful Food Technologies in Nutrika',
    nutrikaTechDesc: 'Nutrika stands out because it combines three internationally recognized food technologies:',
    tech1Name: 'MANGOSELECT®',
    tech1Origin: 'France Technology',
    tech1Desc: 'Mangosteen fruit extract rich in xanthones — powerful natural antioxidants for joint health and inflammation reduction.',
    tech2Name: 'CEREPRON-F®',
    tech2Origin: 'Japan Technology',
    tech2Desc: 'Specialized fermented yeast extract rich in antioxidants and cellular repair nutrients for rejuvenation.',
    tech3Name: 'L-ARABINOSE',
    tech3Origin: 'China Technology',
    tech3Desc: 'Natural plant-based sugar regulator from corn cob fiber for blood sugar control and metabolism support.',
    nutrikaSupports: 'What Can Nutrika Support?',
    nutrikaSupportsDesc: 'Because Nutrika works on inflammation, oxidative stress, and metabolic imbalance, it supports management of:',
    support1: 'Chronic inflammation',
    support2: 'Joint pain and arthritis',
    support3: 'Blood sugar imbalance',
    support4: 'High cholesterol',
    support5: 'Fatigue',
    support6: 'Poor immunity',
    support7: 'Slow metabolism',
    support8: 'Organ stress',
    support9: 'Circulation challenges',
    support10: 'Early degenerative conditions',
    nutrikaImportant: 'Important: Nutrika is not a replacement for prescribed medication. It is a functional food designed to support overall health and recovery under proper guidance.',
    nutrikaDiff: 'Why Nutrika is Different',
    nutrikaDiffDesc: 'Most medications focus on symptom suppression.',
    nutrikaDiff1: 'Painkillers reduce pain.',
    nutrikaDiff2: 'Steroids reduce inflammation temporarily.',
    nutrikaDiff3: 'Some drugs manage sugar levels without correcting metabolic dysfunction.',
    nutrikaDiffFocus: 'Nutrika focuses on:',
    nutrikaDiffF1: 'Supporting the root cellular imbalance',
    nutrikaDiffF2: 'Reducing oxidative damage',
    nutrikaDiffF3: 'Supporting organ function',
    nutrikaDiffF4: 'Restoring natural body balance',
    nutrikaDiffEnd: 'It helps the body return to optimal functionality — the way it was designed to function.',
    nutrikaWealth: 'Health is True Wealth',
    nutrikaWealthDesc: 'When your cells are healthy: Your organs function better. Your blood circulates properly. Your energy increases. Inflammation reduces. Your body heals faster.',
    nutrikaWealthEnd: 'That is the power of functional nutrition.',
    nutrikaExplore: 'Explore the 18 Ingredients →',
    
    // ===== PRODUCTS =====
    productsLabel: 'Our Products',
    productsTitle: '3 Advanced Food Technologies',
    productsDesc: 'Nutrika is formulated using three proprietary food technologies from France and Japan, ensuring maximum bioavailability, efficacy, and safety.',
    product1Name: 'French Bio-Fermentation',
    product1Origin: 'France',
    product1Desc: 'A proprietary fermentation process that enhances nutrient bioavailability by up to 300%. This technology breaks down complex compounds into easily absorbable forms, ensuring your body gets maximum benefit from every ingredient.',
    product2Name: 'Japanese Nano-Emulsion',
    product2Origin: 'Japan',
    product2Desc: 'Particle reduction technology that creates nano-sized droplets for superior absorption at the cellular level. This ensures that active compounds reach target tissues more effectively, increasing potency and reducing waste.',
    product3Name: 'Cell Cleanse Complex',
    product3Origin: 'Global',
    product3Desc: 'A proprietary blend of bio-active compounds designed to support cellular autophagy — the body\'s natural process of clearing damaged cells. This technology is the cornerstone of Nutrika\'s therapeutic range.',
    
    // ===== INGREDIENTS =====
    ingredientsLabel: 'Nutrika Formula',
    ingredientsTitle: '18 Active Ingredients',
    ingredientsDesc: 'Every sachet of Nutrika is a precise fusion of nature and science — ingredients selected from the world\'s most potent botanical and nutritional sources.',
    filterAll: 'All',
    filterImmunity: 'Immunity',
    filterSkin: 'Skin & Beauty',
    filterJoint: 'Joint Health',
    filterSugar: 'Sugar Control',
    filterAntioxidant: 'Anti-Oxidant',
    filterAntiinflammatory: 'Anti-inflammatory',
    
    // ===== BUSINESS =====
    businessLabel: 'The Business Opportunity',
    businessTitle: 'The Choice To Succeed',
    businessDesc: 'Join a compensation plan built to reward action at every level — from your first referral to company profit sharing.',
    comp1: 'Retail Commission',
    comp1Desc: 'Buy at member price, sell at retail price.',
    comp1Highlight: '33% Profit',
    comp2: 'Kick-Start Bonus',
    comp2Desc: 'Get paid for referring another person to the business.',
    comp2Highlight: '$12 · $24 · $144 · $264',
    comp3: 'Upgrade Bonus',
    comp3Desc: 'Earn every time your referred member upgrades to a higher package.',
    comp3Highlight: '$100 Payout',
    comp4: 'Group Binary Bonus',
    comp4Desc: 'Get paid every time you make two corresponding LEFT & RIGHT placements.',
    comp4Highlight: '$100 Payout',
    comp5: 'Partnership Bonus',
    comp5Desc: 'Earn from your team\'s binary income on one leg up to Level 5.',
    comp5Highlight: 'Every 6 Months',
    comp6: 'Performance Bonus',
    comp6Desc: 'Gold Members accumulate PVs converted into CTO shares every 6 months.',
    comp6Highlight: '1 Share = $1,800 USD',
    comp7: 'Personal Bonus',
    comp7Desc: 'Enjoy bonus on every re-purchase made by you.',
    comp7Highlight: '20% on Re-purchase',
    comp8: 'Sales & Purchase Bonus',
    comp8Desc: 'Total income from your team\'s monthly re-purchases, Level 1 to Level 10.',
    comp8Highlight: 'Paid Monthly',
    comp9: 'Leadership Bonus',
    comp9Desc: 'Get paid every 3 months for being a rank achiever.',
    comp9Highlight: 'Every 3 Months',
    comp10: 'Royalty Bonus',
    comp10Desc: 'Hit the last 4 ranks and earn monthly from the company\'s profit shares.',
    comp10Highlight: 'Monthly from Company',
    
    // ===== WHY LIFE NUTRICS =====
    whyTitle: 'Why Life Nutrics?',
    why1: 'Good Leadership',
    why2: 'Earn from One-Side',
    why3: 'Earn from Crosslines via Royalty',
    why4: 'No Monthly Maintenance',
    why5: 'Brand New Global Opportunity',
    why6: 'Highly Effective Products',
    why7: 'Hybrid Pay Plan',
    why8: 'Reliable Withdraw System',
    why9: 'First to Pay 20% on Personal Repurchase',
    why10: 'First to Pay 7% Unilevel',
    why11: 'First to Pay Performance Bonus',
    why12: 'Rank Rewards Every 3 Months',
    why13: '100% Bonus Withdrawal to Members',
    why14: 'Cross-border & International Deliveries',
    
    // ===== PACKAGES =====
    packagesLabel: 'Join Today',
    packagesTitle: 'Membership Packages',
    packagesDesc: 'Choose your entry point. Every package is a gateway to health, income, and community.',
    pkgBronze: 'Bronze',
    pkgBronzeBoxes: '1 Box',
    pkgBronzePV: '40 PV',
    pkgBronzeDesc: 'Entry level. Start experiencing the benefits and earn your first commissions.',
    pkgSilver: 'Silver',
    pkgSilverBoxes: '2 Boxes',
    pkgSilverPV: '80 PV',
    pkgSilverDesc: 'Expand your reach and grow your network with more product to share.',
    pkgSilverPlus: 'Silver Plus',
    pkgSilverPlusBoxes: '12 Boxes',
    pkgSilverPlusPV: '480 PV',
    pkgSilverPlusDesc: 'Unlock higher bonuses and build a serious team with this power package.',
    pkgGold: 'Gold',
    pkgGoldBoxes: '22 Boxes',
    pkgGoldPV: '880 PV',
    pkgGoldDesc: 'Maximum earnings. Unlock performance bonus, CTO shares, and royalty income.',
    pkgPopular: 'Most Popular',
    pkgNote: 'Contact our country office for current package values in US Dollars.',
    
    // ===== CONTACT =====
    contactLabel: 'Get In Touch',
    contactTitle: 'Ready to Elevate Your Life?',
    contactDesc: 'For membership, distributor registration, product purchase, or any enquiry — our team is ready to welcome you.',
    contactOffice: 'Main Office',
    contactOfficeAddr: 'Nyakuron Cultural Centre, Juba, South Sudan',
    contactPhone: 'Phone',
    contactEmail: 'Email',
    contactWebsite: 'Website',
    contactFormTitle: 'Send a Message',
    contactName: 'Your Full Name',
    contactPhoneInput: 'Phone Number',
    contactEmailInput: 'Email Address',
    contactInterest: "I'm interested in...",
    contactOption1: 'Becoming a Member',
    contactOption2: 'Buying Nutrika',
    contactOption3: 'Buying Nu3Coffee',
    contactOption4: 'Becoming a Distributor',
    contactOption5: 'General Enquiry',
    contactMessage: 'Your message or questions...',
    contactSend: 'Send Message',
    
    // ===== LEADERSHIP =====
    leadershipLabel: 'Country Leadership',
    leadershipTitle: 'Meet Our Leader',
    leaderName: 'Mr. Joseph Kenyi',
    leaderTitle: 'Country Manager & Business & Health Consultant',
    leaderQuote: '"Building bridges to enhance quality of life, health, wealth, and lifestyle."',
    leaderExp: 'Years Experience',
    leaderExpDesc: 'Entrepreneurship & income-generating projects',
    leaderMLM: 'MLM Industry',
    leaderMLMDesc: 'Joined in August 2025',
    leaderFounder: 'Founder',
    leaderFounderDesc: 'Life Nutrics South Sudan Limited',
    leaderValue1: 'Leadership',
    leaderValue1Desc: 'Empowering people to lead and succeed',
    leaderValue2: 'Health',
    leaderValue2Desc: 'Promoting wellness for a better life',
    leaderValue3: 'Wealth',
    leaderValue3Desc: 'Creating opportunities for financial freedom',
    leaderValue4: 'Impact',
    leaderValue4Desc: 'Building stronger communities together',
    leaderConnect: 'Connect with Joseph',
    leaderPhone: '+211 900 000 000',
    
    // ===== RESOURCES =====
    resourcesLabel: 'Distributor Resources',
    resourcesTitle: 'Download Documents',
    resourcesDesc: 'Access all the essential documents you need as a Life Nutrics distributor. From compensation plans to registration forms, everything is available for instant download.',
    resourcesCat1: 'Compensation & Business',
    resourcesCat1Desc: 'Everything you need to understand your earning potential and business structure.',
    resourcesCat2: 'Registration & Legal',
    resourcesCat2Desc: 'Official documents for registration, compliance, and legal requirements.',
    resourcesCat3: 'Product & Training',
    resourcesCat3Desc: 'Product guides, training materials, and sales resources for your success.',
    resDoc1: 'Compensation Plan Overview',
    resDoc1Desc: 'Complete breakdown of commission structures, bonuses, and incentives.',
    resDoc2: 'Commission Structure Chart',
    resDoc2Desc: 'Visual breakdown of commission percentages by rank and sales volume.',
    resDoc3: 'Business Plan Template',
    resDoc3Desc: 'Strategic planning document to help you build and grow your distribution network.',
    resDoc4: 'Success Path Checklist',
    resDoc4Desc: 'Step-by-step guide to achieving rank advancement and maximizing earnings.',
    resDoc5: 'Distributor Registration Form',
    resDoc5Desc: 'Official registration form to become a Life Nutrics distributor.',
    resDoc6: 'Terms & Conditions',
    resDoc6Desc: 'Complete terms and conditions for distributors and business partners.',
    resDoc7: 'Company Registration Documents',
    resDoc7Desc: 'Official Life Nutrics SS Limited registration certificates and licenses.',
    resDoc8: 'Privacy Policy & Data Protection',
    resDoc8Desc: 'How we handle and protect your personal and business data.',
    resDoc9: 'Product Catalogue',
    resDoc9Desc: 'Complete product catalogue with ingredients, benefits, and usage guides.',
    resDoc10: 'Distributor Training Manual',
    resDoc10Desc: 'Comprehensive training guide covering product knowledge, sales, and recruitment.',
    resDoc11: 'Sales Script & Pitch Deck',
    resDoc11Desc: 'Proven sales scripts and presentation materials for distributor success.',
    resDoc12: 'Social Media Content Pack',
    resDoc12Desc: 'Ready-to-use social media posts, images, and marketing materials.',
    resQuickAccess: 'Quick Access',
    resQuick1: 'Registration Form',
    resQuick2: 'Compensation Plan',
    resQuick3: 'Product Catalogue',
    resQuick4: 'Training Manual',
    resRequest: "Can't find what you need?",
    resRequestDesc: 'Contact our support team to request specific documents or get help with any questions you may have.',
    resRequestBtn: 'Request Document',
    
    // ===== FOOTER =====
    footerText: 'Nyakuron Cultural Centre, Juba',
    footerGlobal: 'Aligned with Global Life Nutrics Sdn. Bhd. · Malaysia',
    
    // ===== DISCLAIMER =====
    disclaimer: 'Health Notice: Nutrika is a functional food supplement. This information is educational and does not constitute medical advice. Consult your healthcare provider before use if you have existing medical conditions or are on prescription medication.'
  },
  
  // ============================================================
  // KISWAHILI TRANSLATIONS
  // ============================================================
  sw: {
    navHome: 'Nyumbani',
    navProducts: 'Bidhaa',
    navIngredients: 'Viungo',
    navBusiness: 'Biashara',
    navPackages: 'Mifuko',
    navResources: 'Rasilimali',
    navJoin: 'Jiunge Sasa',
    
    heroEyebrow: 'Life Nutrics Sudan Kusini Kituo cha Kimataifa',
    heroTitle: 'Kuinuisha',
    heroTitleAccent: 'Maisha',
    heroSub: 'Afya · Utajiri · Mtindo wa Maisha',
    heroDesc: 'Biashara bora ya afya iliyojikita katika vyakula vya asili vinavyofanya kazi, imejitolea kubadilisha jamii katika Sudan Kusini na kwingineko.',
    heroBtnProducts: 'Chunguza Bidhaa',
    heroBtnBusiness: 'Fursa za Biashara',
    heroStat1Num: '18',
    heroStat1: 'Viungo Vinavyotumika',
    heroStat2Num: '200+',
    heroStat2: 'Magonjwa Yanayoshughulikiwa',
    heroStat3Num: '2025',
    heroStat3: 'Ilianzishwa Juba',
    
    nutrikaLabel: 'Kuhusu Nutrika',
    nutrikaTitle: 'Nutrika ni nini?',
    nutrikaIntro: 'Nutrika ni bidhaa bora ya tiba ya chakula iliyoundwa na viungo 18 vya asili vikali na kuimarishwa na teknolojia tatu za hali ya juu kutoka Ufaransa, Japani, na China.',
    nutrikaDesc: 'Imeundwa kusaidia mwili katika ngazi ya seli, kusaidia kurejesha kazi za kawaida za mwili kupitia sayansi ya lishe.',
    nutrikaNot: 'Nutrika si:',
    nutrikaNot1: 'Mchanganyiko wa mitishamba',
    nutrikaNot2: 'Nyongeza ya synthetiki',
    nutrikaNot3: 'Dawa ya kifamasia ambayo inakandamiza dalili tu kama vile dawa za maumivu',
    nutrikaInstead: 'Badala yake, Nutrika iko katika jamii ya:',
    nutrikaInstead1: 'Tiba ya Chakula Kinachofanya Kazi',
    nutrikaInstead2: 'Sayansi ya Lishe ya Seli',
    nutrikaFocus: 'Inazingatia kulisha, kulinda, na kusaidia mifumo ya asili ya kujirekebisha ya mwili — badala ya kufunika dalili.',
    nutrikaHow: 'Jinsi Nutrika Inavyofanya Kazi Mwilini',
    nutrikaHowDesc: 'Nutrika inafanya kazi katika ngazi ya seli, ambapo magonjwa yote sugu huanzia.',
    nutrikaHowDesc2: 'Changamoto nyingi za muda mrefu — kama vile uvimbe, maumivu ya viungo, uharibifu wa neva, sukari ya juu, uchovu, kinga dhaifu, na matatizo ya viungo — huanza seli zinapokuwa:',
    nutrikaCell1: 'Zilizoharibika',
    nutrikaCell2: 'Zilizovimba',
    nutrikaCell3: 'Zilizooksidishwa',
    nutrikaCell4: 'Zilizozeeka',
    nutrikaCell5: 'Zisizo na virutubishi vya kutosha',
    nutrikaSupport: 'Nutrika inasaidia mwili kwa:',
    nutrikaSupport1: 'Kusaidia ukarabati wa seli zilizoharibika',
    nutrikaSupport2: 'Kukuza uundaji upya wa seli zenye afya',
    nutrikaSupport3: 'Kuhimiza kurejeshwa kwa seli zinazozeeka',
    nutrikaSupport4: 'Kusaidia njia za kuondoa sumu mwilini',
    nutrikaSupport5: 'Kusaidia kurejesha usawa wa kimetaboliki',
    nutrikaSupport6: 'Kusaidia usafishaji wa damu na mzunguko',
    nutrikaSupport7: 'Kuimarisha mwitikio wa asili wa uponyaji wa mwili',
    nutrikaSupportDesc: 'Badala ya kufunika dalili tu, Nutrika inalenga kushughulikia matatizo ya seli kupitia sayansi ya hali ya juu ya lishe.',
    nutrikaTech: 'Teknolojia 3 Zenye Nguvu za Chakula katika Nutrika',
    nutrikaTechDesc: 'Nutrika inajitokeza kwa sababu inachanganya teknolojia tatu za chakula zinazotambulika kimataifa:',
    tech1Name: 'MANGOSELECT®',
    tech1Origin: 'Teknolojia ya Ufaransa',
    tech1Desc: 'Dondoo la matunda ya mangosteen lenye xanthones nyingi — vioksidishaji asili vikali kwa afya ya viungo na kupunguza uvimbe.',
    tech2Name: 'CEREPRON-F®',
    tech2Origin: 'Teknolojia ya Japani',
    tech2Desc: 'Dondoo maalum ya chachu iliyochachushwa yenye vioksidishaji na virutubishi vya kukarabati seli kwa kurejesha nguvu.',
    tech3Name: 'L-ARABINOSE',
    tech3Origin: 'Teknolojia ya China',
    tech3Desc: 'Kidhibiti cha sukari asili kutoka kwa nyuzi za mahindi kwa kudhibiti sukari na kusaidia kimetaboliki.',
    nutrikaSupports: 'Nutrika Inasaidia Nini?',
    nutrikaSupportsDesc: 'Kwa sababu Nutrika inafanya kazi kwenye uvimbe, mkazo wa oksidi, na usawa wa kimetaboliki, inasaidia udhibiti wa:',
    support1: 'Uvimbe sugu',
    support2: 'Maumivu ya viungo na ugonjwa wa yabisi',
    support3: 'Usawa wa sukari ya damu',
    support4: 'Kolesteroli ya juu',
    support5: 'Uchovu',
    support6: 'Kinga dhaifu',
    support7: 'Kimetaboliki polepole',
    support8: 'Mkazo wa viungo',
    support9: 'Changamoto za mzunguko wa damu',
    support10: 'Hali za mapema za kuzorota',
    nutrikaImportant: 'Muhimu: Nutrika si badala ya dawa zilizoagizwa na daktari. Ni chakula kinachofanya kazi kilichoundwa kusaidia afya kwa ujumla na kupona chini ya mwongozo sahihi.',
    nutrikaDiff: 'Kwa nini Nutrika ni Tofauti',
    nutrikaDiffDesc: 'Dawa nyingi huzingatia kukandamiza dalili.',
    nutrikaDiff1: 'Dawa za maumivu hupunguza maumivu.',
    nutrikaDiff2: 'Steroidi hupunguza uvimbe kwa muda.',
    nutrikaDiff3: 'Baadhi ya dawa hudhibiti viwango vya sukari bila kusahihisha matatizo ya kimetaboliki.',
    nutrikaDiffFocus: 'Nutrika inazingatia:',
    nutrikaDiffF1: 'Kusaidia usawa wa seli',
    nutrikaDiffF2: 'Kupunguza uharibifu wa oksidi',
    nutrikaDiffF3: 'Kusaidia kazi za viungo',
    nutrikaDiffF4: 'Kurejesha usawa wa asili wa mwili',
    nutrikaDiffEnd: 'Inasaidia mwili kurudi kwenye utendaji bora — jinsi ulivyoundwa kufanya kazi.',
    nutrikaWealth: 'Afya ni Utajiri wa Kweli',
    nutrikaWealthDesc: 'Seli zako zinapokuwa na afya: Viungo vyako hufanya kazi vizuri. Damu yako huzunguka vizuri. Nguvu zako huongezeka. Uvimbe hupungua. Mwili wako hupona haraka.',
    nutrikaWealthEnd: 'Huo ni uwezo wa lishe inayofanya kazi.',
    nutrikaExplore: 'Chunguza Viungo 18 →',
    
    productsLabel: 'Bidhaa Zetu',
    productsTitle: 'Teknolojia 3 za Hali ya Juu za Chakula',
    productsDesc: 'Nutrika imeundwa kwa kutumia teknolojia tatu za kipekee za chakula kutoka Ufaransa na Japani, kuhakikisha ufyonzaji wa juu, ufanisi, na usalama.',
    product1Name: 'Uchachushaji wa Bio wa Ufaransa',
    product1Origin: 'Ufaransa',
    product1Desc: 'Mchakato wa kipekee wa uchachushaji unaoongeza upatikanaji wa virutubishi kwa hadi 300%. Teknolojia hii inavunja misombo changamfu katika fomu zinazofyonzwa kwa urahisi.',
    product2Name: 'Nano-Emulsion ya Kijapani',
    product2Origin: 'Japani',
    product2Desc: 'Teknolojia ya kupunguza chembe inayounda matone ya nano kwa ufyonzaji bora katika ngazi ya seli, kuongeza nguvu na kupunguza upotevu.',
    product3Name: 'Kichanganya cha Kusafisha Seli',
    product3Origin: 'Global',
    product3Desc: 'Mchanganyiko wa kipekee wa misombo hai iliyoundwa kusaidia autophagy ya seli — mchakato wa asili wa mwili wa kuondoa seli zilizoharibika.',
    
    ingredientsLabel: 'Muundo wa Nutrika',
    ingredientsTitle: 'Viungo 18 Vinavyotumika',
    ingredientsDesc: 'Kila mfuko wa Nutrika ni mchanganyiko sahihi wa asili na sayansi — viungo vilivyochaguliwa kutoka vyanzo vikali zaidi vya mimea na lishe duniani.',
    filterAll: 'Zote',
    filterImmunity: 'Kinga',
    filterSkin: 'Ngozi na Urembo',
    filterJoint: 'Afya ya Viungo',
    filterSugar: 'Udhibiti wa Sukari',
    filterAntioxidant: 'Kinza-oksidishaji',
    filterAntiinflammatory: 'Kinza-uvimbe',
    
    businessLabel: 'Fursa ya Biashara',
    businessTitle: 'Chaguo la Kufanikiwa',
    businessDesc: 'Jiunge na mpango wa fidia ulioundwa kutuzia hatua katika kila ngazi — kutoka kwa rufaa yako ya kwanza hadi kugawana faida ya kampuni.',
    comp1: 'Tume ya Rejareja',
    comp1Desc: 'Nunua kwa bei ya mwanachama, uza kwa bei ya rejareja.',
    comp1Highlight: '33% Faida',
    comp2: 'Bonasi ya Kuanzisha',
    comp2Desc: 'Lipwa kwa kumrejelea mtu mwingine kwenye biashara.',
    comp2Highlight: '$12 · $24 · $144 · $264',
    comp3: 'Bonasi ya Kuboresha',
    comp3Desc: 'Pata kila wakati mwanachama wako anapoboresha hadi mfuko wa juu.',
    comp3Highlight: '$100 Malipo',
    comp4: 'Bonasi ya Kikundi cha Binary',
    comp4Desc: 'Lipwa kila wakati unapofanya uwekaji wa KUSHOTO na KULIA unaolingana.',
    comp4Highlight: '$100 Malipo',
    comp5: 'Bonasi ya Ushirikiano',
    comp5Desc: 'Pata kutoka kwa mapato ya binary ya timu yako kwenye mguu mmoja hadi Ngazi ya 5.',
    comp5Highlight: 'Kila Miezi 6',
    comp6: 'Bonasi ya Utendaji',
    comp6Desc: 'Wanachama wa Dhahabu hukusanya PV zinazobadilishwa kuwa hisa za CTO kila miezi 6.',
    comp6Highlight: '1 Hisa = $1,800 USD',
    comp7: 'Bonasi ya Kibinafsi',
    comp7Desc: 'Furahia bonasi kwa kila ununuzi tena unaofanywa na wewe.',
    comp7Highlight: '20% kwa Ununuzi Tena',
    comp8: 'Bonasi ya Mauzo na Ununuzi',
    comp8Desc: 'Mapato yote kutoka kwa ununuzi tena wa kila mwezi wa timu yako, Ngazi ya 1 hadi 10.',
    comp8Highlight: 'Inalipwa Kila Mwezi',
    comp9: 'Bonasi ya Uongozi',
    comp9Desc: 'Lipwa kila miezi 3 kwa kuwa mwenye cheo.',
    comp9Highlight: 'Kila Miezi 3',
    comp10: 'Bonasi ya Mrabaha',
    comp10Desc: 'Fikia ngazi 4 za mwisho na pata kila mwezi kutoka kwa hisa za faida za kampuni.',
    comp10Highlight: 'Kila Mwezi kutoka Kampuni',
    
    whyTitle: 'Kwa nini Life Nutrics?',
    why1: 'Uongozi Mzuri',
    why2: 'Pata kutoka Upande Mmoja',
    why3: 'Pata kutoka Mistari Mtambuka kupitia Mrabaha',
    why4: 'Hakuna Matengenezo ya Kila Mwezi',
    why5: 'Fursa Mpya ya Kimataifa',
    why6: 'Bidhaa Zinazofaa Sana',
    why7: 'Mpango wa Malipo Mchanganyiko',
    why8: 'Mfumo wa Kuondoa Pesa wa Kuaminika',
    why9: 'Wa Kwanza Kulipa 20% kwa Ununuzi Tena wa Kibinafsi',
    why10: 'Wa Kwanza Kulipa 7% Unilevel',
    why11: 'Wa Kwanza Kulipa Bonasi ya Utendaji',
    why12: 'Zawadi za Ngazi Kila Miezi 3',
    why13: '100% Uondoaji wa Bonasi kwa Wanachama',
    why14: 'Usafirishaji wa Kuvuka Mipaka na Kimataifa',
    
    packagesLabel: 'Jiunge Leo',
    packagesTitle: 'Mifuko ya Uanachama',
    packagesDesc: 'Chagua sehemu yako ya kuingia. Kila mfuko ni lango la afya, mapato, na jamii.',
    pkgBronze: 'Shaba',
    pkgBronzeBoxes: 'Sanduku 1',
    pkgBronzePV: '40 PV',
    pkgBronzeDesc: 'Kiwango cha kuingia. Anza kupata manufaa na pata tume zako za kwanza.',
    pkgSilver: 'Fedha',
    pkgSilverBoxes: 'Sanduku 2',
    pkgSilverPV: '80 PV',
    pkgSilverDesc: 'Panua ufikiaji wako na kukuza mtandao wako kwa bidhaa zaidi ya kushiriki.',
    pkgSilverPlus: 'Fedha Plus',
    pkgSilverPlusBoxes: 'Sanduku 12',
    pkgSilverPlusPV: '480 PV',
    pkgSilverPlusDesc: 'Fungua bonasi za juu na ujenge timu kubwa na mfuko huu wa nguvu.',
    pkgGold: 'Dhahabu',
    pkgGoldBoxes: 'Sanduku 22',
    pkgGoldPV: '880 PV',
    pkgGoldDesc: 'Mapato ya juu. Fungua bonasi ya utendaji, hisa za CTO, na mapato ya mrabaha.',
    pkgPopular: 'Inayojulikana Sana',
    pkgNote: 'Wasiliana na ofisi yetu ya nchi kwa thamani za sasa za mifuko katika Dola za Marekani.',
    
    contactLabel: 'Wasiliana Nasi',
    contactTitle: 'Uko Tayari Kuinuisha Maisha Yako?',
    contactDesc: 'Kwa uanachama, usajili wa wasambazaji, ununuzi wa bidhaa, au swali lolote — timu yetu iko tayari kukukaribisha.',
    contactOffice: 'Ofisi Kuu',
    contactOfficeAddr: 'Nyakuron Cultural Centre, Juba, Sudan Kusini',
    contactPhone: 'Simu',
    contactEmail: 'Barua Pepe',
    contactWebsite: 'Tovuti',
    contactFormTitle: 'Tuma Ujumbe',
    contactName: 'Jina Lako Kamili',
    contactPhoneInput: 'Nambari ya Simu',
    contactEmailInput: 'Barua Pepe',
    contactInterest: 'Ninavutiwa na...',
    contactOption1: 'Kuwa Mwanachama',
    contactOption2: 'Kununua Nutrika',
    contactOption3: 'Kununua Nu3Coffee',
    contactOption4: 'Kuwa Msambazaji',
    contactOption5: 'Swali la Jumla',
    contactMessage: 'Ujumbe wako au maswali...',
    contactSend: 'Tuma Ujumbe',
    
    leadershipLabel: 'Uongozi wa Nchi',
    leadershipTitle: 'Kutana na Kiongozi Wetu',
    leaderName: 'Bw. Joseph Kenyi',
    leaderTitle: 'Meneja wa Nchi na Mshauri wa Biashara na Afya',
    leaderQuote: '"Kujenga madaraja kuimarisha ubora wa maisha, afya, utajiri, na mtindo wa maisha."',
    leaderExp: 'Miaka ya Uzoefu',
    leaderExpDesc: 'Ujasiriamali na miradi ya kuzalisha mapato',
    leaderMLM: 'Sekta ya MLM',
    leaderMLMDesc: 'Alijiunga Agosti 2025',
    leaderFounder: 'Mwanzilishi',
    leaderFounderDesc: 'Life Nutrics South Sudan Limited',
    leaderValue1: 'Uongozi',
    leaderValue1Desc: 'Kuwawezesha watu kuongoza na kufanikiwa',
    leaderValue2: 'Afya',
    leaderValue2Desc: 'Kukuza afya kwa maisha bora',
    leaderValue3: 'Utajiri',
    leaderValue3Desc: 'Kuunda fursa za uhuru wa kifedha',
    leaderValue4: 'Athari',
    leaderValue4Desc: 'Kujenga jamii zenye nguvu pamoja',
    leaderConnect: 'Wasiliana na Joseph',
    leaderPhone: '+211 900 000 000',
    
    resourcesLabel: 'Rasilimali za Wasambazaji',
    resourcesTitle: 'Pakua Nyaraka',
    resourcesDesc: 'Pata nyaraka zote muhimu unazohitaji kama msambazaji wa Life Nutrics. Kuanzia mipango ya fidia hadi fomu za usajili, kila kitu kinapatikana kwa upakuaji wa papo hapo.',
    resourcesCat1: 'Fidia na Biashara',
    resourcesCat1Desc: 'Kila kitu unachohitaji kuelewa uwezo wako wa mapato na muundo wa biashara.',
    resourcesCat2: 'Usajili na Sheria',
    resourcesCat2Desc: 'Nyaraka rasmi za usajili, uzingatiaji, na mahitaji ya kisheria.',
    resourcesCat3: 'Bidhaa na Mafunzo',
    resourcesCat3Desc: 'Miongozo ya bidhaa, nyenzo za mafunzo, na rasilimali za mauzo kwa mafanikio yako.',
    resDoc1: 'Muhtasari wa Mpango wa Fidia',
    resDoc1Desc: 'Uchambuzi kamili wa miundo ya tume, bonasi, na motisha.',
    resDoc2: 'Chati ya Muundo wa Tume',
    resDoc2Desc: 'Uchanganuzi wa asilimia za tume kulingana na cheo na kiasi cha mauzo.',
    resDoc3: 'Mfano wa Mpango wa Biashara',
    resDoc3Desc: 'Hati ya upangaji wa kimkakati kukusaidia kujenga na kukuza mtandao wako wa usambazaji.',
    resDoc4: 'Orodha ya Njia ya Mafanikio',
    resDoc4Desc: 'Mwongozo wa hatua kwa hatua wa kufikia kupanda ngazi na kuongeza mapato.',
    resDoc5: 'Fomu ya Usajili wa Msambazaji',
    resDoc5Desc: 'Fomu rasmi ya usajili kuwa msambazaji wa Life Nutrics.',
    resDoc6: 'Masharti na Mazingira',
    resDoc6Desc: 'Masharti na mazingira kamili kwa wasambazaji na washirika wa biashara.',
    resDoc7: 'Nyaraka za Usajili wa Kampuni',
    resDoc7Desc: 'Vyeti na leseni rasmi za usajili wa Life Nutrics SS Limited.',
    resDoc8: 'Sera ya Faragha na Ulinzi wa Data',
    resDoc8Desc: 'Jinsi tunavyoshughulikia na kulinda data yako ya kibinafsi na biashara.',
    resDoc9: 'Katalogi ya Bidhaa',
    resDoc9Desc: 'Katalogi kamili ya bidhaa na viungo, faida, na mwongozo wa matumizi.',
    resDoc10: 'Mwongozo wa Mafunzo kwa Wasambazaji',
    resDoc10Desc: 'Mwongozo kamili wa mafunzo unaojumuisha maarifa ya bidhaa, mauzo, na kuajiri.',
    resDoc11: 'Hati ya Mauzo na Uwasilishaji',
    resDoc11Desc: 'Hati zilizothibitishwa za mauzo na nyenzo za uwasilishaji kwa mafanikio ya msambazaji.',
    resDoc12: 'Mfuko wa Maudhui ya Mitandao ya Kijamii',
    resDoc12Desc: 'Maudhui tayari ya matumizi kwenye mitandao ya kijamii, picha, na nyenzo za uuzaji.',
    resQuickAccess: 'Ufikiaji wa Haraka',
    resQuick1: 'Fomu ya Usajili',
    resQuick2: 'Mpango wa Fidia',
    resQuick3: 'Katalogi ya Bidhaa',
    resQuick4: 'Mwongozo wa Mafunzo',
    resRequest: 'Huwezi kupata unachohitaji?',
    resRequestDesc: 'Wasiliana na timu yetu ya msaada kuomba nyaraka maalum au kupata msaada kwa maswali yoyote.',
    resRequestBtn: 'Omba Hati',
    
    footerText: 'Nyakuron Cultural Centre, Juba',
    footerGlobal: 'Inaambatana na Global Life Nutrics Sdn. Bhd. · Malaysia',
    disclaimer: 'Ilani ya Afya: Nutrika ni nyongeza ya chakula inayofanya kazi. Taarifa hii ni ya kielimu na haijumuishi ushauri wa matibabu. Wasiliana na mtoa huduma wako wa afya kabla ya kutumia ikiwa una hali za kiafya zilizopo au uko kwenye dawa zilizoagizwa.'
  },
  
  // ============================================================
  // ARABIC TRANSLATIONS
  // ============================================================
  ar: {
    navHome: 'الرئيسية',
    navProducts: 'المنتجات',
    navIngredients: 'المكونات',
    navBusiness: 'الأعمال',
    navPackages: 'الباقات',
    navResources: 'الموارد',
    navJoin: 'انضم الآن',
    
    heroEyebrow: 'لايف نيوتركس جنوب السودان المركز الدولي',
    heroTitle: 'رفع المستوى',
    heroTitleAccent: 'للحياة',
    heroSub: 'الصحة · الثروة · نمط الحياة',
    heroDesc: 'مؤسسة صحية متميزة متجذرة في الأطعمة الوظيفية الطبيعية، مكرسة لتحويل المجتمعات في جنوب السودان وخارجه.',
    heroBtnProducts: 'استكشف المنتجات',
    heroBtnBusiness: 'فرصة عمل',
    heroStat1Num: '١٨',
    heroStat1: 'مكونات نشطة',
    heroStat2Num: '٢٠٠+',
    heroStat2: 'الأمراض التي تعالج',
    heroStat3Num: '٢٠٢٥',
    heroStat3: 'تأسست في جوبا',
    
    nutrikaLabel: 'عن نيوتريكا',
    nutrikaTitle: 'ما هي نيوتريكا؟',
    nutrikaIntro: 'نيوتريكا هو منتج علاج غذائي وظيفي متميز تم تركيبه من 18 مكونًا طبيعيًا قويًا ومعزز بثلاث تقنيات غذائية متقدمة من فرنسا واليابان والصين.',
    nutrikaDesc: 'تم تصميمه لدعم الجسم على المستوى الخلوي، للمساعدة في استعادة وظائف الجسم الطبيعية من خلال علم التغذية.',
    nutrikaNot: 'نيوتريكا ليست:',
    nutrikaNot1: 'خليط عشبي',
    nutrikaNot2: 'مكمل اصطناعي',
    nutrikaNot3: 'دواء صيدلاني يثبط الأعراض فقط مثل مسكنات الألم',
    nutrikaInstead: 'بدلاً من ذلك، تندرج نيوتريكا ضمن فئة:',
    nutrikaInstead1: 'العلاج الغذائي الوظيفي',
    nutrikaInstead2: 'علم التغذية الخلوية',
    nutrikaFocus: 'تركز على تغذية وحماية ودعم أنظمة الإصلاح الطبيعية للجسم — بدلاً من إخفاء الأعراض.',
    nutrikaHow: 'كيف تعمل نيوتريكا في الجسم',
    nutrikaHowDesc: 'تعمل نيوتريكا على المستوى الخلوي، حيث تبدأ جميع الحالات المزمنة.',
    nutrikaHowDesc2: 'تبدأ العديد من التحديات المزمنة — مثل الالتهابات وآلام المفاصل وتلف الأعصاب وارتفاع سكر الدم والتعب وضعف المناعة وخلل الأعضاء — عندما تصبح الخلايا:',
    nutrikaCell1: 'تالفة',
    nutrikaCell2: 'ملتهبة',
    nutrikaCell3: 'مؤكسدة',
    nutrikaCell4: 'متقدمة في السن',
    nutrikaCell5: 'ناقصة المغذيات',
    nutrikaSupport: 'تدعم نيوتريكا الجسم من خلال:',
    nutrikaSupport1: 'دعم إصلاح الخلايا التالفة',
    nutrikaSupport2: 'تعزيز تجديد الخلايا السليمة',
    nutrikaSupport3: 'تشجيع تجديد الخلايا المتقدمة في السن',
    nutrikaSupport4: 'دعم مسارات إزالة السموم',
    nutrikaSupport5: 'المساعدة في استعادة التوازن الأيضي الطبيعي',
    nutrikaSupport6: 'دعم تنقية الدم والدورة الدموية',
    nutrikaSupport7: 'تعزيز استجابة الشفاء الطبيعية للجسم',
    nutrikaSupportDesc: 'بدلاً من مجرد تغطية الأعراض، تركز نيوتريكا على معالجة الخلل الخلوي الأساسي من خلال علم التغذية المتقدم.',
    nutrikaTech: 'تقنيات الغذاء الثلاث القوية في نيوتريكا',
    nutrikaTechDesc: 'تتميز نيوتريكا لأنها تجمع بين ثلاث تقنيات غذائية معترف بها دوليًا:',
    tech1Name: 'MANGOSELECT®',
    tech1Origin: 'التقنية الفرنسية',
    tech1Desc: 'مستخلص فاكهة المانجوستين الغني بالزانثونات — مضادات أكسدة طبيعية قوية لصحة المفاصل وتقليل الالتهابات.',
    tech2Name: 'CEREPRON-F®',
    tech2Origin: 'التقنية اليابانية',
    tech2Desc: 'مستخلص خميرة مخمرة متخصص غني بمضادات الأكسدة ومغذيات إصلاح الخلايا للتجديد.',
    tech3Name: 'L-ARABINOSE',
    tech3Origin: 'التقنية الصينية',
    tech3Desc: 'منظم سكر طبيعي من ألياف كوز الذرة للتحكم في سكر الدم ودعم التمثيل الغذائي.',
    nutrikaSupports: 'ماذا تدعم نيوتريكا؟',
    nutrikaSupportsDesc: 'لأن نيوتريكا تعمل على الالتهابات والإجهاد التأكسدي والخلل الأيضي، فهي تدعم إدارة:',
    support1: 'الالتهابات المزمنة',
    support2: 'آلام المفاصل والتهاب المفاصل',
    support3: 'اختلال سكر الدم',
    support4: 'ارتفاع الكوليسترول',
    support5: 'التعب',
    support6: 'ضعف المناعة',
    support7: 'بطء التمثيل الغذائي',
    support8: 'إجهاد الأعضاء',
    support9: 'مشاكل الدورة الدموية',
    support10: 'الحالات التنكسية المبكرة',
    nutrikaImportant: 'هام: نيوتريكا ليست بديلاً عن الأدوية الموصوفة. إنها غذاء وظيفي مصمم لدعم الصحة العامة والتعافي تحت إشراف مناسب.',
    nutrikaDiff: 'لماذا نيوتريكا مختلفة',
    nutrikaDiffDesc: 'تركز معظم الأدوية على قمع الأعراض.',
    nutrikaDiff1: 'مسكنات الألم تقلل الألم.',
    nutrikaDiff2: 'الستيرويدات تقلل الالتهاب مؤقتًا.',
    nutrikaDiff3: 'بعض الأدوية تدير مستويات السكر دون تصحيح الخلل الأيضي.',
    nutrikaDiffFocus: 'تركز نيوتريكا على:',
    nutrikaDiffF1: 'دعم الخلل الخلوي الجذري',
    nutrikaDiffF2: 'تقليل الضرر التأكسدي',
    nutrikaDiffF3: 'دعم وظائف الأعضاء',
    nutrikaDiffF4: 'استعادة توازن الجسم الطبيعي',
    nutrikaDiffEnd: 'تساعد الجسم على العودة إلى الوظيفة المثلى — بالطريقة التي صمم ليعمل بها.',
    nutrikaWealth: 'الصحة هي الثروة الحقيقية',
    nutrikaWealthDesc: 'عندما تكون خلاياك صحية: تعمل أعضاؤك بشكل أفضل. يدور دمك بشكل صحيح. تزداد طاقتك. يقل الالتهاب. يشفى جسمك بشكل أسرع.',
    nutrikaWealthEnd: 'هذه هي قوة التغذية الوظيفية.',
    nutrikaExplore: 'استكشف المكونات الثمانية عشر →',
    
    productsLabel: 'منتجاتنا',
    productsTitle: '٣ تقنيات غذائية متقدمة',
    productsDesc: 'تم تركيبة نيوتريكا باستخدام ثلاث تقنيات غذائية حصرية من فرنسا واليابان، لضمان أقصى توفر حيوي وفعالية وسلامة.',
    product1Name: 'التخمير الحيوي الفرنسي',
    product1Origin: 'فرنسا',
    product1Desc: 'عملية تخمير حصرية تعزز التوافر الحيوي للمغذيات بنسبة تصل إلى 300%. تعمل هذه التقنية على تفكيك المركبات المعقدة إلى أشكال سهلة الامتصاص.',
    product2Name: 'المستحلب النانوي الياباني',
    product2Origin: 'اليابان',
    product2Desc: 'تقنية تقليل الجسيمات التي تخلق قطرات بحجم النانو لامتصاص فائق على المستوى الخلوي، مما يزيد من الفعالية ويقلل من الهدر.',
    product3Name: 'مركب تطهير الخلايا',
    product3Origin: 'عالمي',
    product3Desc: 'مزيج حصري من المركبات النشطة بيولوجيًا المصممة لدعم الالتهام الذاتي الخلوي — العملية الطبيعية للجسم للتخلص من الخلايا التالفة.',
    
    ingredientsLabel: 'تركيبة نيوتريكا',
    ingredientsTitle: '١٨ مكونًا نشطًا',
    ingredientsDesc: 'كل كيس من نيوتريكا هو اندماج دقيق بين الطبيعة والعلم — مكونات تم اختيارها من أقوى المصادر النباتية والغذائية في العالم.',
    filterAll: 'الكل',
    filterImmunity: 'المناعة',
    filterSkin: 'البشرة والجمال',
    filterJoint: 'صحة المفاصل',
    filterSugar: 'التحكم في السكر',
    filterAntioxidant: 'مضاد للأكسدة',
    filterAntiinflammatory: 'مضاد للالتهابات',
    
    businessLabel: 'فرصة العمل',
    businessTitle: 'الاختيار للنجاح',
    businessDesc: 'انضم إلى خطة تعويضات مصممة لمكافأة العمل في كل مستوى — من أول إحالة لك إلى مشاركة أرباح الشركة.',
    comp1: 'عمولة التجزئة',
    comp1Desc: 'اشترِ بسعر العضو، وبع بسعر التجزئة.',
    comp1Highlight: '٣٣% ربح',
    comp2: 'مكافأة الانطلاق',
    comp2Desc: 'احصل على أجر لإحالة شخص آخر إلى العمل.',
    comp2Highlight: '٢٦٤ · ١٤٤ · ٢٤ · ١٢ دولار',
    comp3: 'مكافأة الترقية',
    comp3Desc: 'اربح في كل مرة يقوم فيها عضوك المحال بالترقية إلى باقة أعلى.',
    comp3Highlight: '١٠٠ دولار دفعة',
    comp4: 'مكافأة المجموعة الثنائية',
    comp4Desc: 'احصل على أجر في كل مرة تقوم فيها بعمل وضعين متطابقين يسار ويمين.',
    comp4Highlight: '١٠٠ دولار دفعة',
    comp5: 'مكافأة الشراكة',
    comp5Desc: 'اربح من دخل فريقك الثنائي على ساق واحدة حتى المستوى 5.',
    comp5Highlight: 'كل ٦ أشهر',
    comp6: 'مكافأة الأداء',
    comp6Desc: 'يجمع الأعضاء الذهبيون نقاط PV التي يتم تحويلها إلى أسهم CTO كل 6 أشهر.',
    comp6Highlight: '١ سهم = ١٬٨٠٠ دولار أمريكي',
    comp7: 'المكافأة الشخصية',
    comp7Desc: 'استمتع بمكافأة على كل عملية إعادة شراء تقوم بها.',
    comp7Highlight: '٢٠% على إعادة الشراء',
    comp8: 'مكافأة المبيعات والمشتريات',
    comp8Desc: 'إجمالي الدخل من عمليات إعادة الشراء الشهرية لفريقك، من المستوى 1 إلى 10.',
    comp8Highlight: 'تدفع شهريًا',
    comp9: 'مكافأة القيادة',
    comp9Desc: 'احصل على أجر كل 3 أشهر لكونك صاحب رتبة.',
    comp9Highlight: 'كل ٣ أشهر',
    comp10: 'مكافأة الإتاوة',
    comp10Desc: 'احصل على المراتب الأربع الأخيرة واربح شهريًا من حصص أرباح الشركة.',
    comp10Highlight: 'شهريًا من الشركة',
    
    whyTitle: 'لماذا لايف نيوتركس؟',
    why1: 'قيادة جيدة',
    why2: 'اربح من جهة واحدة',
    why3: 'اربح من الخطوط المتقاطعة عبر الإتاوة',
    why4: 'لا توجد صيانة شهرية',
    why5: 'فرصة عالمية جديدة تمامًا',
    why6: 'منتجات عالية الفعالية',
    why7: 'خطة دفع هجينة',
    why8: 'نظام سحب موثوق',
    why9: 'الأول في دفع ٢٠% على إعادة الشراء الشخصي',
    why10: 'الأول في دفع ٧% يونيليفل',
    why11: 'الأول في دفع مكافأة الأداء',
    why12: 'مكافآت الرتب كل ٣ أشهر',
    why13: 'سحب ١٠٠% من المكافآت للأعضاء',
    why14: 'التوصيل عبر الحدود والدولي',
    
    packagesLabel: 'انضم اليوم',
    packagesTitle: 'باقات العضوية',
    packagesDesc: 'اختر نقطة دخولك. كل باقة هي بوابة للصحة والدخل والمجتمع.',
    pkgBronze: 'برونزي',
    pkgBronzeBoxes: 'صندوق ١',
    pkgBronzePV: '٤٠ PV',
    pkgBronzeDesc: 'مستوى الدخول. ابدأ في تجربة الفوائد واربح عمولاتك الأولى.',
    pkgSilver: 'فضي',
    pkgSilverBoxes: 'صندوقان',
    pkgSilverPV: '٨٠ PV',
    pkgSilverDesc: 'وسع نطاق وصولك وانمِ شبكتك بالمزيد من المنتجات للمشاركة.',
    pkgSilverPlus: 'فضي بلس',
    pkgSilverPlusBoxes: '١٢ صندوقًا',
    pkgSilverPlusPV: '٤٨٠ PV',
    pkgSilverPlusDesc: 'افتح مكافآت أعلى وابنِ فريقًا جادًا بهذه الباقة القوية.',
    pkgGold: 'ذهبي',
    pkgGoldBoxes: '٢٢ صندوقًا',
    pkgGoldPV: '٨٨٠ PV',
    pkgGoldDesc: 'أقصى أرباح. افتح مكافأة الأداء وأسهم CTO ودخل الإتاوة.',
    pkgPopular: 'الأكثر شهرة',
    pkgNote: 'اتصل بمكتبنا القطري لمعرفة قيم الباقات الحالية بالدولار الأمريكي.',
    
    contactLabel: 'تواصل معنا',
    contactTitle: 'هل أنت مستعد لرفع مستوى حياتك؟',
    contactDesc: 'للعضوية أو تسجيل الموزعين أو شراء المنتجات أو أي استفسار — فريقنا جاهز للترحيب بك.',
    contactOffice: 'المكتب الرئيسي',
    contactOfficeAddr: 'مركز نياكورون الثقافي، جوبا، جنوب السودان',
    contactPhone: 'الهاتف',
    contactEmail: 'البريد الإلكتروني',
    contactWebsite: 'الموقع الإلكتروني',
    contactFormTitle: 'أرسل رسالة',
    contactName: 'اسمك الكامل',
    contactPhoneInput: 'رقم الهاتف',
    contactEmailInput: 'البريد الإلكتروني',
    contactInterest: 'أنا مهتم بـ...',
    contactOption1: 'أن أصبح عضوًا',
    contactOption2: 'شراء نيوتريكا',
    contactOption3: 'شراء Nu3Coffee',
    contactOption4: 'أن أصبح موزعًا',
    contactOption5: 'استفسار عام',
    contactMessage: 'رسالتك أو أسئلتك...',
    contactSend: 'أرسل الرسالة',
    
    leadershipLabel: 'قيادة الدولة',
    leadershipTitle: 'تعرف على قائدنا',
    leaderName: 'السيد جوزيف كيني',
    leaderTitle: 'مدير الدولة ومستشار الأعمال والصحة',
    leaderQuote: '"بناء جسور لتعزيز جودة الحياة والصحة والثروة ونمط الحياة."',
    leaderExp: 'سنوات من الخبرة',
    leaderExpDesc: 'ريادة الأعمال والمشاريع المدرة للدخل',
    leaderMLM: 'صناعة التسويق الشبكي',
    leaderMLMDesc: 'انضم في أغسطس ٢٠٢٥',
    leaderFounder: 'المؤسس',
    leaderFounderDesc: 'شركة لايف نيوتركس جنوب السودان المحدودة',
    leaderValue1: 'القيادة',
    leaderValue1Desc: 'تمكين الناس من القيادة والنجاح',
    leaderValue2: 'الصحة',
    leaderValue2Desc: 'تعزيز العافية لحياة أفضل',
    leaderValue3: 'الثروة',
    leaderValue3Desc: 'خلق فرص للحرية المالية',
    leaderValue4: 'التأثير',
    leaderValue4Desc: 'بناء مجتمعات أقوى معًا',
    leaderConnect: 'تواصل مع جوزيف',
    leaderPhone: '+٢١١ ٩٠٠ ٠٠٠ ٠٠٠',
    
    resourcesLabel: 'موارد الموزعين',
    resourcesTitle: 'تحميل المستندات',
    resourcesDesc: 'احصل على جميع المستندات الأساسية التي تحتاجها كموزع لـ Life Nutrics. من خطط التعويض إلى نماذج التسجيل، كل شيء متاح للتحميل الفوري.',
    resourcesCat1: 'التعويض والأعمال',
    resourcesCat1Desc: 'كل ما تحتاجه لفهم إمكانيات أرباحك وهيكل عملك.',
    resourcesCat2: 'التسجيل والقانون',
    resourcesCat2Desc: 'المستندات الرسمية للتسجيل والامتثال والمتطلبات القانونية.',
    resourcesCat3: 'المنتج والتدريب',
    resourcesCat3Desc: 'أدلة المنتج ومواد التدريب وموارد المبيعات لنجاحك.',
    resDoc1: 'نظرة عامة على خطة التعويض',
    resDoc1Desc: 'تحليل كامل لهياكل العمولات والمكافآت والحوافز.',
    resDoc2: 'مخطط هيكل العمولة',
    resDoc2Desc: 'تحليل بصري لنسب العمولات حسب الرتبة وحجم المبيعات.',
    resDoc3: 'نموذج خطة العمل',
    resDoc3Desc: 'وثيقة تخطيط استراتيجي لمساعدتك في بناء وتنمية شبكة التوزيع الخاصة بك.',
    resDoc4: 'قائمة مسار النجاح',
    resDoc4Desc: 'دليل خطوة بخطوة لتحقيق التقدم في الرتب وتعظيم الأرباح.',
    resDoc5: 'نموذج تسجيل الموزع',
    resDoc5Desc: 'نموذج التسجيل الرسمي لتصبح موزعًا لـ Life Nutrics.',
    resDoc6: 'الشروط والأحكام',
    resDoc6Desc: 'الشروط والأحكام الكاملة للموزعين والشركاء التجاريين.',
    resDoc7: 'وثائق تسجيل الشركة',
    resDoc7Desc: 'شهادات وتراخيص التسجيل الرسمية لشركة Life Nutrics SS Limited.',
    resDoc8: 'سياسة الخصوصية وحماية البيانات',
    resDoc8Desc: 'كيف نتعامل مع بياناتك الشخصية والتجارية ونحميها.',
    resDoc9: 'كتالوج المنتجات',
    resDoc9Desc: 'كتالوج المنتجات الكامل مع المكونات والفوائد وأدلة الاستخدام.',
    resDoc10: 'دليل تدريب الموزعين',
    resDoc10Desc: 'دليل تدريب شامل يغطي المعرفة بالمنتجات والمبيعات والتوظيف.',
    resDoc11: 'نص المبيعات وعرض العرض',
    resDoc11Desc: 'نصوص مبيعات مثبتة ومواد عرض لنجاح الموزع.',
    resDoc12: 'حزمة محتوى وسائل التواصل الاجتماعي',
    resDoc12Desc: 'منشورات جاهزة للاستخدام على وسائل التواصل الاجتماعي وصور ومواد تسويقية.',
    resQuickAccess: 'وصول سريع',
    resQuick1: 'نموذج التسجيل',
    resQuick2: 'خطة التعويض',
    resQuick3: 'كتالوج المنتجات',
    resQuick4: 'دليل التدريب',
    resRequest: 'لا يمكنك العثور على ما تحتاجه؟',
    resRequestDesc: 'اتصل بفريق الدعم لدينا لطلب مستندات محددة أو الحصول على مساعدة في أي أسئلة قد تكون لديك.',
    resRequestBtn: 'طلب مستند',
    
    footerText: 'مركز نياكورون الثقافي، جوبا',
    footerGlobal: 'متوافق مع Global Life Nutrics Sdn. Bhd. · ماليزيا',
    disclaimer: 'إشعار صحي: نيوتريكا هو مكمل غذائي وظيفي. هذه المعلومات تعليمية ولا تشكل نصيحة طبية. استشر مقدم الرعاية الصحية الخاص بك قبل الاستخدام إذا كنت تعاني من حالات طبية موجودة أو تتناول أدوية موصوفة.'
  },
  
  // ============================================================
  // FRENCH TRANSLATIONS
  // ============================================================
  fr: {
    navHome: 'Accueil',
    navProducts: 'Produits',
    navIngredients: 'Ingrédients',
    navBusiness: 'Affaires',
    navPackages: 'Forfaits',
    navResources: 'Ressources',
    navJoin: 'Rejoindre',
    
    heroEyebrow: 'Life Nutrics Soudan du Sud Hub International',
    heroTitle: 'Élever',
    heroTitleAccent: 'des Vies',
    heroSub: 'Santé · Richesse · Mode de Vie',
    heroDesc: 'Une entreprise de bien-être de premier plan enracinée dans les aliments fonctionnels naturels, dédiée à la transformation des communautés à travers le Soudan du Sud et au-delà.',
    heroBtnProducts: 'Explorer les Produits',
    heroBtnBusiness: 'Opportunité d\'Affaires',
    heroStat1Num: '18',
    heroStat1: 'Ingrédients Actifs',
    heroStat2Num: '200+',
    heroStat2: 'Affections Traitées',
    heroStat3Num: '2025',
    heroStat3: 'Établi à Juba',
    
    nutrikaLabel: 'À propos de Nutrika',
    nutrikaTitle: 'Qu\'est-ce que Nutrika ?',
    nutrikaIntro: 'Nutrika est un produit de thérapie alimentaire fonctionnelle de qualité supérieure formulé avec 18 ingrédients naturels puissants et amélioré avec trois technologies alimentaires avancées de France, du Japon et de Chine.',
    nutrikaDesc: 'Il est conçu pour soutenir le corps au niveau cellulaire, aidant à restaurer la fonction corporelle normale grâce à une science nutritionnelle.',
    nutrikaNot: 'Nutrika n\'est pas :',
    nutrikaNot1: 'Un mélange à base de plantes',
    nutrikaNot2: 'Un supplément synthétique',
    nutrikaNot3: 'Un médicament pharmaceutique qui ne fait que supprimer les symptômes comme les analgésiques',
    nutrikaInstead: 'Au lieu de cela, Nutrika entre dans la catégorie :',
    nutrikaInstead1: 'Thérapie Alimentaire Fonctionnelle',
    nutrikaInstead2: 'Science Nutritionnelle Cellulaire',
    nutrikaFocus: 'Il se concentre sur la nutrition, la protection et le soutien des systèmes de réparation naturels du corps — plutôt que de masquer les symptômes.',
    nutrikaHow: 'Comment Nutrika agit dans le corps',
    nutrikaHowDesc: 'Nutrika agit au niveau cellulaire, où toutes les affections chroniques commencent.',
    nutrikaHowDesc2: 'De nombreux défis chroniques — tels que l\'inflammation, les douleurs articulaires, les lésions nerveuses, l\'hyperglycémie, la fatigue, la faiblesse immunitaire et le dysfonctionnement des organes — commencent lorsque les cellules deviennent :',
    nutrikaCell1: 'Endommagées',
    nutrikaCell2: 'Enflammées',
    nutrikaCell3: 'Oxydées',
    nutrikaCell4: 'Vieillies',
    nutrikaCell5: 'Carencées en nutriments',
    nutrikaSupport: 'Nutrika soutient le corps en :',
    nutrikaSupport1: 'Soutenant la réparation des cellules endommagées',
    nutrikaSupport2: 'Promouvant la régénération cellulaire saine',
    nutrikaSupport3: 'Encourageant le rajeunissement des cellules vieillissantes',
    nutrikaSupport4: 'Soutenant les voies de détoxification',
    nutrikaSupport5: 'Aidant à rétablir l\'équilibre métabolique normal',
    nutrikaSupport6: 'Soutenant la purification du sang et la circulation',
    nutrikaSupport7: 'Améliorant la réponse de guérison naturelle du corps',
    nutrikaSupportDesc: 'Au lieu de simplement couvrir les symptômes, Nutrika se concentre sur la résolution du dysfonctionnement cellulaire sous-jacent grâce à une science nutritionnelle avancée.',
    nutrikaTech: 'Les 3 Technologies Alimentaires Puissantes dans Nutrika',
    nutrikaTechDesc: 'Nutrika se distingue car elle combine trois technologies alimentaires reconnues internationalement :',
    tech1Name: 'MANGOSELECT®',
    tech1Origin: 'Technologie Française',
    tech1Desc: 'Extrait de fruit de mangoustan riche en xanthones — de puissants antioxydants naturels pour la santé des articulations et la réduction de l\'inflammation.',
    tech2Name: 'CEREPRON-F®',
    tech2Origin: 'Technologie Japonaise',
    tech2Desc: 'Extrait de levure fermentée spécialisé riche en antioxydants et en nutriments de réparation cellulaire pour le rajeunissement.',
    tech3Name: 'L-ARABINOSE',
    tech3Origin: 'Technologie Chinoise',
    tech3Desc: 'Régulateur de sucre naturel à base de fibres de maïs pour le contrôle de la glycémie et le soutien du métabolisme.',
    nutrikaSupports: 'Que peut soutenir Nutrika ?',
    nutrikaSupportsDesc: 'Parce que Nutrika agit sur l\'inflammation, le stress oxydatif et le déséquilibre métabolique, elle soutient la gestion de :',
    support1: 'L\'inflammation chronique',
    support2: 'Les douleurs articulaires et l\'arthrite',
    support3: 'Le déséquilibre de la glycémie',
    support4: 'L\'hypercholestérolémie',
    support5: 'La fatigue',
    support6: 'La faiblesse immunitaire',
    support7: 'Le métabolisme lent',
    support8: 'Le stress des organes',
    support9: 'Les problèmes de circulation',
    support10: 'Les affections dégénératives précoces',
    nutrikaImportant: 'Important : Nutrika n\'est pas un remplacement des médicaments prescrits. C\'est un aliment fonctionnel conçu pour soutenir la santé globale et la récupération sous une guidance appropriée.',
    nutrikaDiff: 'Pourquoi Nutrika est Différent',
    nutrikaDiffDesc: 'La plupart des médicaments se concentrent sur la suppression des symptômes.',
    nutrikaDiff1: 'Les analgésiques réduisent la douleur.',
    nutrikaDiff2: 'Les stéroïdes réduisent l\'inflammation temporairement.',
    nutrikaDiff3: 'Certains médicaments gèrent les niveaux de sucre sans corriger le dysfonctionnement métabolique.',
    nutrikaDiffFocus: 'Nutrika se concentre sur :',
    nutrikaDiffF1: 'Soutenir le déséquilibre cellulaire fondamental',
    nutrikaDiffF2: 'Réduire les dommages oxydatifs',
    nutrikaDiffF3: 'Soutenir la fonction des organes',
    nutrikaDiffF4: 'Rétablir l\'équilibre naturel du corps',
    nutrikaDiffEnd: 'Il aide le corps à retrouver une fonctionnalité optimale — la façon dont il a été conçu pour fonctionner.',
    nutrikaWealth: 'La Santé est la Vraie Richesse',
    nutrikaWealthDesc: 'Lorsque vos cellules sont en bonne santé : Vos organes fonctionnent mieux. Votre sang circule correctement. Votre énergie augmente. L\'inflammation diminue. Votre corps guérit plus rapidement.',
    nutrikaWealthEnd: 'C\'est le pouvoir de la nutrition fonctionnelle.',
    nutrikaExplore: 'Explorer les 18 Ingrédients →',
    
    productsLabel: 'Nos Produits',
    productsTitle: '3 Technologies Alimentaires Avancées',
    productsDesc: 'Nutrika est formulé en utilisant trois technologies alimentaires exclusives de France et du Japon, garantissant une biodisponibilité, une efficacité et une sécurité maximales.',
    product1Name: 'Bio-Fermentation Française',
    product1Origin: 'France',
    product1Desc: 'Un processus de fermentation exclusif qui améliore la biodisponibilité des nutriments jusqu\'à 300%. Cette technologie décompose les composés complexes en formes facilement absorbables.',
    product2Name: 'Nano-Émulsion Japonaise',
    product2Origin: 'Japon',
    product2Desc: 'Technologie de réduction des particules qui crée des gouttelettes de taille nanométrique pour une absorption supérieure au niveau cellulaire, augmentant la puissance et réduisant les déchets.',
    product3Name: 'Complexe de Nettoyage Cellulaire',
    product3Origin: 'Mondial',
    product3Desc: 'Un mélange exclusif de composés bioactifs conçu pour soutenir l\'autophagie cellulaire — le processus naturel du corps d\'élimination des cellules endommagées.',
    
    ingredientsLabel: 'Formule Nutrika',
    ingredientsTitle: '18 Ingrédients Actifs',
    ingredientsDesc: 'Chaque sachet de Nutrika est une fusion précise de nature et de science — des ingrédients sélectionnés parmi les sources botaniques et nutritionnelles les plus puissantes du monde.',
    filterAll: 'Tous',
    filterImmunity: 'Immunité',
    filterSkin: 'Peau et Beauté',
    filterJoint: 'Santé des Articulations',
    filterSugar: 'Contrôle du Sucre',
    filterAntioxidant: 'Antioxydant',
    filterAntiinflammatory: 'Anti-inflammatoire',
    
    businessLabel: 'L\'Opportunité d\'Affaires',
    businessTitle: 'Le Choix de Réussir',
    businessDesc: 'Rejoignez un plan de rémunération conçu pour récompenser l\'action à chaque niveau — de votre premier parrainage au partage des bénéfices de l\'entreprise.',
    comp1: 'Commission de Détail',
    comp1Desc: 'Achetez au prix membre, vendez au prix de détail.',
    comp1Highlight: '33% de Profit',
    comp2: 'Bonus de Démarrage',
    comp2Desc: 'Soyez payé pour parrainer une autre personne dans l\'entreprise.',
    comp2Highlight: '12$ · 24$ · 144$ · 264$',
    comp3: 'Bonus de Montée en Grade',
    comp3Desc: 'Gagnez à chaque fois que votre membre parrainé passe à un forfait supérieur.',
    comp3Highlight: '100$ de Paiement',
    comp4: 'Bonus Binaire de Groupe',
    comp4Desc: 'Soyez payé à chaque fois que vous faites deux placements GAUCHE et DROITE correspondants.',
    comp4Highlight: '100$ de Paiement',
    comp5: 'Bonus de Partenariat',
    comp5Desc: 'Gagnez grâce au revenu binaire de votre équipe sur une jambe jusqu\'au Niveau 5.',
    comp5Highlight: 'Tous les 6 Mois',
    comp6: 'Bonus de Performance',
    comp6Desc: 'Les membres Or accumulent des PV convertis en actions CTO tous les 6 mois.',
    comp6Highlight: '1 Action = 1 800$ USD',
    comp7: 'Bonus Personnel',
    comp7Desc: 'Profitez d\'un bonus sur chaque réachat effectué par vous.',
    comp7Highlight: '20% sur les Réachats',
    comp8: 'Bonus de Vente et d\'Achat',
    comp8Desc: 'Revenu total des réachats mensuels de votre équipe, Niveau 1 à 10.',
    comp8Highlight: 'Payé Mensuellement',
    comp9: 'Bonus de Leadership',
    comp9Desc: 'Soyez payé tous les 3 mois pour être un leader de rang.',
    comp9Highlight: 'Tous les 3 Mois',
    comp10: 'Bonus de Royauté',
    comp10Desc: 'Atteignez les 4 derniers rangs et gagnez mensuellement grâce aux parts de bénéfices de l\'entreprise.',
    comp10Highlight: 'Mensuel de l\'Entreprise',
    
    whyTitle: 'Pourquoi Life Nutrics ?',
    why1: 'Bon Leadership',
    why2: 'Gagnez d\'un Côté',
    why3: 'Gagnez des Lignes Croisées via la Royauté',
    why4: 'Pas de Maintenance Mensuelle',
    why5: 'Nouvelle Opportunité Mondiale',
    why6: 'Produits Très Efficaces',
    why7: 'Plan de Rémunération Hybride',
    why8: 'Système de Retrait Fiable',
    why9: 'Premier à Payer 20% sur les Réachats Personnels',
    why10: 'Premier à Payer 7% Unilevel',
    why11: 'Premier à Payer le Bonus de Performance',
    why12: 'Récompenses de Rang Tous les 3 Mois',
    why13: 'Retrait de 100% des Bonus aux Membres',
    why14: 'Livraisons Transfrontalières et Internationales',
    
    packagesLabel: 'Rejoignez Aujourd\'hui',
    packagesTitle: 'Forfaits d\'Adhésion',
    packagesDesc: 'Choisissez votre point d\'entrée. Chaque forfait est une porte vers la santé, le revenu et la communauté.',
    pkgBronze: 'Bronze',
    pkgBronzeBoxes: '1 Boîte',
    pkgBronzePV: '40 PV',
    pkgBronzeDesc: 'Niveau d\'entrée. Commencez à expérimenter les bienfaits et gagnez vos premières commissions.',
    pkgSilver: 'Argent',
    pkgSilverBoxes: '2 Boîtes',
    pkgSilverPV: '80 PV',
    pkgSilverDesc: 'Élargissez votre portée et développez votre réseau avec plus de produits à partager.',
    pkgSilverPlus: 'Argent Plus',
    pkgSilverPlusBoxes: '12 Boîtes',
    pkgSilverPlusPV: '480 PV',
    pkgSilverPlusDesc: 'Débloquez des bonus plus élevés et construisez une équipe sérieuse avec ce forfait puissant.',
    pkgGold: 'Or',
    pkgGoldBoxes: '22 Boîtes',
    pkgGoldPV: '880 PV',
    pkgGoldDesc: 'Revenus maximaux. Débloquez le bonus de performance, les actions CTO et les revenus de royauté.',
    pkgPopular: 'Le Plus Populaire',
    pkgNote: 'Contactez notre bureau national pour les valeurs actuelles des forfaits en dollars américains.',
    
    contactLabel: 'Contactez-Nous',
    contactTitle: 'Prêt à Élever Votre Vie ?',
    contactDesc: 'Pour l\'adhésion, l\'enregistrement des distributeurs, l\'achat de produits ou toute demande — notre équipe est prête à vous accueillir.',
    contactOffice: 'Bureau Principal',
    contactOfficeAddr: 'Centre Culturel Nyakuron, Juba, Soudan du Sud',
    contactPhone: 'Téléphone',
    contactEmail: 'Email',
    contactWebsite: 'Site Web',
    contactFormTitle: 'Envoyer un Message',
    contactName: 'Votre Nom Complet',
    contactPhoneInput: 'Numéro de Téléphone',
    contactEmailInput: 'Adresse Email',
    contactInterest: 'Je suis intéressé par...',
    contactOption1: 'Devenir Membre',
    contactOption2: 'Acheter Nutrika',
    contactOption3: 'Acheter Nu3Coffee',
    contactOption4: 'Devenir Distributeur',
    contactOption5: 'Demande Générale',
    contactMessage: 'Votre message ou questions...',
    contactSend: 'Envoyer le Message',
    
    leadershipLabel: 'Leadership du Pays',
    leadershipTitle: 'Rencontrez Notre Leader',
    leaderName: 'M. Joseph Kenyi',
    leaderTitle: 'Directeur National et Consultant en Affaires et Santé',
    leaderQuote: '"Construire des ponts pour améliorer la qualité de vie, la santé, la richesse et le mode de vie."',
    leaderExp: 'Années d\'Expérience',
    leaderExpDesc: 'Entrepreneuriat et projets générateurs de revenus',
    leaderMLM: 'Industrie MLM',
    leaderMLMDesc: 'Rejoint en août 2025',
    leaderFounder: 'Fondateur',
    leaderFounderDesc: 'Life Nutrics South Sudan Limited',
    leaderValue1: 'Leadership',
    leaderValue1Desc: 'Autonomiser les gens pour diriger et réussir',
    leaderValue2: 'Santé',
    leaderValue2Desc: 'Promouvoir le bien-être pour une vie meilleure',
    leaderValue3: 'Richesse',
    leaderValue3Desc: 'Créer des opportunités pour la liberté financière',
    leaderValue4: 'Impact',
    leaderValue4Desc: 'Construire des communautés plus fortes ensemble',
    leaderConnect: 'Connectez-vous avec Joseph',
    leaderPhone: '+211 900 000 000',
    
    resourcesLabel: 'Ressources pour Distributeurs',
    resourcesTitle: 'Télécharger les Documents',
    resourcesDesc: 'Accédez à tous les documents essentiels dont vous avez besoin en tant que distributeur Life Nutrics. Des plans de rémunération aux formulaires d\'inscription, tout est disponible en téléchargement instantané.',
    resourcesCat1: 'Rémunération et Affaires',
    resourcesCat1Desc: 'Tout ce dont vous avez besoin pour comprendre votre potentiel de revenus et votre structure d\'entreprise.',
    resourcesCat2: 'Inscription et Juridique',
    resourcesCat2Desc: 'Documents officiels pour l\'inscription, la conformité et les exigences légales.',
    resourcesCat3: 'Produit et Formation',
    resourcesCat3Desc: 'Guides produits, supports de formation et ressources de vente pour votre succès.',
    resDoc1: 'Aperçu du Plan de Rémunération',
    resDoc1Desc: 'Décomposition complète des structures de commission, bonus et incitations.',
    resDoc2: 'Tableau des Structures de Commission',
    resDoc2Desc: 'Décomposition visuelle des pourcentages de commission par rang et volume de ventes.',
    resDoc3: 'Modèle de Plan d\'Affaires',
    resDoc3Desc: 'Document de planification stratégique pour vous aider à construire et développer votre réseau de distribution.',
    resDoc4: 'Liste de Contrôle du Chemin du Succès',
    resDoc4Desc: 'Guide étape par étape pour atteindre l\'avancement de rang et maximiser les revenus.',
    resDoc5: 'Formulaire d\'Inscription du Distributeur',
    resDoc5Desc: 'Formulaire d\'inscription officiel pour devenir distributeur Life Nutrics.',
    resDoc6: 'Conditions Générales',
    resDoc6Desc: 'Conditions générales complètes pour les distributeurs et les partenaires commerciaux.',
    resDoc7: 'Documents d\'Enregistrement de la Société',
    resDoc7Desc: 'Certificats et licences d\'enregistrement officiels de Life Nutrics SS Limited.',
    resDoc8: 'Politique de Confidentialité et Protection des Données',
    resDoc8Desc: 'Comment nous traitons et protégeons vos données personnelles et professionnelles.',
    resDoc9: 'Catalogue de Produits',
    resDoc9Desc: 'Catalogue complet des produits avec ingrédients, avantages et guides d\'utilisation.',
    resDoc10: 'Manuel de Formation du Distributeur',
    resDoc10Desc: 'Guide de formation complet couvrant la connaissance des produits, les ventes et le recrutement.',
    resDoc11: 'Script de Vente et Présentation',
    resDoc11Desc: 'Scripts de vente éprouvés et supports de présentation pour le succès du distributeur.',
    resDoc12: 'Pack de Contenu pour les Réseaux Sociaux',
    resDoc12Desc: 'Publications prêtes à l\'emploi pour les réseaux sociaux, images et supports marketing.',
    resQuickAccess: 'Accès Rapide',
    resQuick1: 'Formulaire d\'Inscription',
    resQuick2: 'Plan de Rémunération',
    resQuick3: 'Catalogue de Produits',
    resQuick4: 'Manuel de Formation',
    resRequest: 'Vous ne trouvez pas ce que vous cherchez ?',
    resRequestDesc: 'Contactez notre équipe d\'assistance pour demander des documents spécifiques ou obtenir de l\'aide pour toutes vos questions.',
    resRequestBtn: 'Demander un Document',
    
    footerText: 'Centre Culturel Nyakuron, Juba',
    footerGlobal: 'Aligné avec Global Life Nutrics Sdn. Bhd. · Malaisie',
    disclaimer: 'Avis de Santé : Nutrika est un complément alimentaire fonctionnel. Ces informations sont éducatives et ne constituent pas un avis médical. Consultez votre professionnel de santé avant utilisation si vous avez des conditions médicales existantes ou si vous prenez des médicaments sur ordonnance.'
  }
};

// ============================================================
// LANGUAGE UTILITY FUNCTIONS
// ============================================================

// Get current language from localStorage or default
function getCurrentLanguage() {
  return localStorage.getItem('preferredLanguage') || 'en';
}

// Set language and apply immediately without reload
function setLanguage(lang) {
  if (translations[lang]) {
    localStorage.setItem('preferredLanguage', lang);
    
    // Set RTL for Arabic
    if (lang === 'ar') {
      document.documentElement.dir = 'rtl';
      document.documentElement.lang = 'ar';
    } else {
      document.documentElement.dir = 'ltr';
      document.documentElement.lang = lang;
    }
    
    // Apply translations
    applyTranslations();
    
    // Update UI
    updateLanguageUI();
    
    // Close dropdown
    const dropdown = document.getElementById('langDropdown');
    if (dropdown) dropdown.classList.remove('open');
  }
}

// Get translation for a specific key
function t(key) {
  const lang = getCurrentLanguage();
  const keys = key.split('.');
  let value = translations[lang];
  for (const k of keys) {
    if (value && value[k] !== undefined) {
      value = value[k];
    } else {
      return key;
    }
  }
  return value || key;
}

// Apply translations to all elements with data-i18n attribute
function applyTranslations() {
  const elements = document.querySelectorAll('[data-i18n]');
  elements.forEach(el => {
    const key = el.getAttribute('data-i18n');
    const translation = t(key);
    if (translation && translation !== key) {
      // Handle different element types
      if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
        if (el.hasAttribute('data-i18n-placeholder')) {
          el.placeholder = translation;
        } else {
          el.value = translation;
        }
      } else if (el.tagName === 'IMG' && el.hasAttribute('data-i18n-alt')) {
        el.alt = translation;
      } else {
        el.textContent = translation;
      }
    }
  });
}

// Update language switcher UI
function updateLanguageUI() {
  const lang = getCurrentLanguage();
  const currentLangSpan = document.getElementById('currentLang');
  const langOptions = document.querySelectorAll('.lang-option');
  
  const langNames = {
    en: 'English',
    sw: 'Kiswahili',
    ar: 'العربية',
    fr: 'Français'
  };
  
  const langFlags = {
    en: '🇬🇧',
    sw: '🇹🇿',
    ar: '🇸🇦',
    fr: '🇫🇷'
  };
  
  if (currentLangSpan) {
    currentLangSpan.textContent = langNames[lang] || 'English';
  }
  
  // Update toggle flag
  const toggleFlag = document.querySelector('.lang-toggle .lang-flag');
  if (toggleFlag) {
    toggleFlag.textContent = langFlags[lang] || '🌍';
  }
  
  langOptions.forEach(option => {
    const dataLang = option.getAttribute('data-lang');
    if (dataLang === lang) {
      option.classList.add('active');
    } else {
      option.classList.remove('active');
    }
  });
}

// ============================================================
// INITIALIZE ON PAGE LOAD
// ============================================================
document.addEventListener('DOMContentLoaded', function() {
  // Set initial RTL for Arabic
  const currentLang = getCurrentLanguage();
  if (currentLang === 'ar') {
    document.documentElement.dir = 'rtl';
    document.documentElement.lang = 'ar';
  } else {
    document.documentElement.dir = 'ltr';
    document.documentElement.lang = currentLang;
  }
  
  // Apply translations
  applyTranslations();
  
  // Update language UI
  updateLanguageUI();
  
  // Language toggle click - open/close dropdown
  const langToggle = document.getElementById('langToggle');
  const langDropdown = document.getElementById('langDropdown');
  
  if (langToggle && langDropdown) {
    langToggle.addEventListener('click', function(e) {
      e.preventDefault();
      e.stopPropagation();
      langDropdown.classList.toggle('open');
    });
  }
  
  // Language option click - select language
  document.querySelectorAll('.lang-option').forEach(btn => {
    btn.addEventListener('click', function(e) {
      e.preventDefault();
      e.stopPropagation();
      const lang = this.getAttribute('data-lang');
      if (lang) {
        setLanguage(lang);
      }
    });
  });
  
  // Close dropdown when clicking outside
  document.addEventListener('click', function(e) {
    const dropdown = document.getElementById('langDropdown');
    const toggle = document.getElementById('langToggle');
    if (dropdown && toggle) {
      if (!toggle.contains(e.target) && !dropdown.contains(e.target)) {
        dropdown.classList.remove('open');
      }
    }
  });
});